services:
  sysken-pay:
    container_name: sysken-pay
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/go/src/app
      - go_modules:/go/pkg/mod
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    env_file:
      - .env
    environment:
      - MYSQL_HOST=db
    tty: true
    networks:
      - private-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8
    container_name: sysken-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    ports:
      - 53306:3306
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - private-net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  private-net:
    driver: bridge

volumes:
  mysql_data:
  go_modules:
